param(
    [string]$StudioProject = 'D:\Micu\RTTWorkspace\titan_uart_test'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$canonicalRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\titan_rtthread')).Path
$studioRoot = Join-Path $StudioProject 'src'
# All project-owned runtime sources/headers required by the UART path.
$fileNames = @(
    'smart_hand_protocol.c',
    'smart_hand_protocol.h',
    'smart_hand_uart.c',
    # smart_hand_uart.c includes this header and calls its AITRUST encoder, but
    # neither file was listed, so the one automated artefact gate could not see
    # them: a repo-side edit left unsynced would still print "check passed".
    'smart_hand_status_telemetry.c',
    'smart_hand_status_telemetry.h',
    'smart_hand_vision_state.c',
    'smart_hand_vision_state.h',
    'smart_hand_sequence_guard.c',
    'smart_hand_sequence_guard.h',
    'titan_trust_model.c',
    'titan_trust_model.h',
    'titan_trust_runtime.c',
    'titan_trust_runtime.h',
    'grip_policy.c',
    'grip_policy.h',
    'grip_pose_bank.c',
    'grip_pose_bank.h',
    'servo_safety_gate.h',
    'eight_servo_safety_gate.c',
    'eight_servo_safety_gate.h',
    'eight_servo_pose_bank.c',
    'eight_servo_pose_bank.h',
    'scs0009_packet.c',
    'scs0009_packet.h',
    'scs0009_stream.c',
    'scs0009_stream.h',
    'scs0009_transaction.c',
    'scs0009_transaction.h',
    'servo_group_readonly.c',
    'servo_group_readonly.h',
    'servo_bus_readonly_rt.c',
    'servo_bus_readonly_rt.h',
    # Voice extension (passive integration, 2026-09-23). voice_model_data.*
    # is generated by smart_hand/titan_ai/voice/train_voice_kws.py; the copies
    # under titan_rtthread/ are the deployment source of truth, mirroring the
    # existing titan_trust_model.* arrangement.
    'voice_config.h',
    'voice_audio.c',
    'voice_audio.h',
    'voice_audio_titan.c',
    'voice_audio_titan.h',
    'voice_features.c',
    'voice_features.h',
    'voice_kws.c',
    'voice_kws.h',
    'voice_model_data.c',
    'voice_model_data.h',
    'voice_app.c',
    'voice_app.h',
    'voice_app_titan.c',
    'voice_app_titan.h'
)

if (-not (Test-Path -LiteralPath $studioRoot -PathType Container)) {
    throw "RT-Thread Studio source directory not found: $studioRoot"
}

$mismatchFound = $false
$results = foreach ($fileName in $fileNames) {
    $canonicalPath = Join-Path $canonicalRoot $fileName
    $studioPath = Join-Path $studioRoot $fileName
    if (-not (Test-Path -LiteralPath $canonicalPath -PathType Leaf)) {
        throw "Canonical source file not found: $canonicalPath"
    }
    if (-not (Test-Path -LiteralPath $studioPath -PathType Leaf)) {
        throw "Studio source file not found: $studioPath"
    }

    $canonicalHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $canonicalPath).Hash
    $studioHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $studioPath).Hash
    $matches = $canonicalHash -eq $studioHash
    if (-not $matches) {
        $mismatchFound = $true
    }
    [pscustomobject]@{
        File = $fileName
        Match = $matches
        CanonicalSHA256 = $canonicalHash
        StudioSHA256 = $studioHash
    }
}

$results | Format-Table -AutoSize
if ($mismatchFound) {
    throw 'Titan source trees differ; inspect them before building or copying files.'
}
Write-Host 'Titan source sync check passed.'
Write-Host 'Note: hash match is not ARM link evidence; run check_titan_linkage.ps1 after Studio Build.'
